services:
  web_migrate: 
      build:
        context: .
      command: python manage.py migrate
      volumes: 
        - .:/code
      depends_on:
      - db
  web: 
      build:
        context: .
      env_file: .env
      command: python manage.py runserver 0.0.0.0:8000
      volumes: 
        - .:/code
      ports: 
        - '8000:8000'
      depends_on:
      - web_migrate
  db:
    image: postgres:16
    env_file: .env
  